# SPDX-FileCopyrightText: 2023 Genome Research Ltd.
#
# SPDX-License-Identifier: MIT

FROM python:3.12

WORKDIR /app

ENV FLASK_ENV=development
ENV PYTHONPATH=/app
ENV PYTHONDONTWRITEBYTECODE 1

RUN apt-get update -y
RUN apt-get install -y python3-pip python3-setuptools

RUN pip3 install --upgrade setuptools

COPY ./app/setup.py .

COPY ./app/requirements.txt .
RUN pip3 --no-cache-dir install -r requirements.txt

# We install the tol-sdk here in editable mode
VOLUME ["/packages"]

COPY ./app /app
COPY ./migrations /migrations

CMD if [ -d /packages/tol-sdk/src ] ; then pip3 install --editable /packages/tol-sdk[api-base,elastic,postgresql,prefect,sheets]; fi; \
    flask --app run run --debug --port 80 --host 0.0.0.0
