# SPDX-FileCopyrightText: 2023 Genome Research Ltd.
#
# SPDX-License-Identifier: MIT

include:
  - project: 'tol/tol-core'
    ref: v1.7.10
    file: '/gitlab/app.yml'

variables:
  APP_NAME: tol-portal
  SERVICE_NAME: portal
  DISABLE_UI_LINT: "true"
