# SPDX-FileCopyrightText: 2023 Genome Research Ltd.
#
# SPDX-License-Identifier: MIT

include:
  - template: "Verify/Accessibility.gitlab-ci.yml"
  - project: 'tol/tol-core'
    ref: v1.5.5
    file: '/gitlab/app.yml'

variables:
  APP_NAME: tol-portal
  SERVICE_NAME: portal
  DISABLE_UI_LINT: "true"

stages:
  - lint
  - build
  - unit test
  - system test
  - review
  - accessibility
  - scan
  - scan container
  - dast
  - cleanup
  - deploy

a11y:
  variables:
    REVIEW_URL: https://${CI_PROJECT_NAME}-${CI_COMMIT_REF_SLUG}.review.tol.sanger.ac.uk
    a11y_urls: "$REVIEW_URL $REVIEW_URL/species $REVIEW_URL/manifests"
  script:
    - |
      mkdir -p reports

      pa11y-ci -j --config "/pa11y-configs/.pa11yci" $a11y_urls > reports/gl-accessibility.json

      for url in $a11y_urls
      do
        filename="reports/$(echo $url | sed -E 's/^https?:\/\///' | sed -E 's/\//-/g')-accessibility.html"
        pa11y --config "/pa11y-configs/pa11y.json" --ignore-ssl-errors=true $url | tee $filename > /dev/null
      done

  rules:
    - if: $DISABLE_REVIEW_APPS
      when: never
    - if: $CI_COMMIT_BRANCH !~ /^TOL.*$/
      when: never
    - exists:
      - "${APP_NAME}-ui/**/*"




