# SPDX-FileCopyrightText: 2023 Genome Research Ltd.
#
# SPDX-License-Identifier: MIT

include:
  - project: 'tol/tol-core'
    ref: '69ce1b5ce76cd13bf9d0a23ec3a09912b3d59a8a'
    file: '/gitlab/app.yml'

variables:
  APP_NAME: tol-portal
  SERVICE_NAME: portal
